version: "3.9"

services:
  webapi:
    build:
      context: ./GameBackend.API
      dockerfile: Dockerfile
    container_name: game_backend_api
    ports:
      - "7239:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - dp_keys:/root/.aspnet/DataProtection-Keys

  pythonapp:
    build:
      context: ./GameData
      dockerfile: Dockerfile
    container_name: game_data
    volumes:
      - ./GameData/Files:/app/Files
      - ./GameData/Reports:/app/Reports

volumes:
  dp_keys:
